
ALTER TABLE LA_CARD_LABEL_VALUE MODIFY CARD_LABEL_VALUE_STRING VARCHAR(128);

DROP FUNCTION LA_FUN_CARD_LABEL_VALUE_ENFORCE;

DELIMITER //

CREATE FUNCTION LA_FUN_CARD_LABEL_VALUE_ENFORCE (
    CARD_LABEL_VALUE_TYPE ENUM('NULL', 'STRING', 'TIMESTAMP', 'INT', 'CARD', 'USER', 'LIST'),
    CARD_LABEL_VALUE_STRING VARCHAR(128),
    CARD_LABEL_VALUE_TIMESTAMP TIMESTAMP,
    CARD_LABEL_VALUE_INT INTEGER,
    CARD_LABEL_VALUE_CARD_FK INTEGER,
    CARD_LABEL_VALUE_USER_FK INTEGER,
    CARD_LABEL_VALUE_LIST_VALUE_FK INTEGER)
    RETURNS BOOLEAN
    DETERMINISTIC
    BEGIN
        RETURN (CARD_LABEL_VALUE_TYPE IN ('NULL', 'STRING', 'TIMESTAMP', 'INT', 'CARD', 'USER', 'LIST')) AND (CASE
            WHEN CARD_LABEL_VALUE_TYPE = 'NULL' THEN
              CARD_LABEL_VALUE_STRING 	IS NULL AND
              CARD_LABEL_VALUE_TIMESTAMP 	IS NULL AND
              CARD_LABEL_VALUE_INT 		IS NULL AND
              CARD_LABEL_VALUE_CARD_FK	IS NULL AND
              CARD_LABEL_VALUE_USER_FK	IS NULL AND
              CARD_LABEL_VALUE_LIST_VALUE_FK IS NULL
            WHEN CARD_LABEL_VALUE_TYPE = 'STRING' THEN
              CARD_LABEL_VALUE_STRING 	IS NOT NULL AND
              CARD_LABEL_VALUE_TIMESTAMP 	IS NULL AND
              CARD_LABEL_VALUE_INT 		IS NULL AND
              CARD_LABEL_VALUE_CARD_FK	IS NULL AND
              CARD_LABEL_VALUE_USER_FK	IS NULL AND
              CARD_LABEL_VALUE_LIST_VALUE_FK IS NULL
            WHEN CARD_LABEL_VALUE_TYPE = 'TIMESTAMP' THEN
              CARD_LABEL_VALUE_STRING 	IS NULL AND
              CARD_LABEL_VALUE_TIMESTAMP 	IS NOT NULL AND
              CARD_LABEL_VALUE_INT 		IS NULL AND
              CARD_LABEL_VALUE_CARD_FK	IS NULL AND
              CARD_LABEL_VALUE_USER_FK	IS NULL AND
              CARD_LABEL_VALUE_LIST_VALUE_FK IS NULL
            WHEN CARD_LABEL_VALUE_TYPE = 'INT' THEN
              CARD_LABEL_VALUE_STRING 	IS NULL AND
              CARD_LABEL_VALUE_TIMESTAMP 	IS NULL AND
              CARD_LABEL_VALUE_INT 		IS NOT NULL AND
              CARD_LABEL_VALUE_CARD_FK	IS NULL AND
              CARD_LABEL_VALUE_USER_FK	IS NULL AND
              CARD_LABEL_VALUE_LIST_VALUE_FK IS NULL
            WHEN CARD_LABEL_VALUE_TYPE = 'CARD' THEN
              CARD_LABEL_VALUE_STRING 	IS NULL AND
              CARD_LABEL_VALUE_TIMESTAMP 	IS NULL AND
              CARD_LABEL_VALUE_INT 		IS NULL AND
              CARD_LABEL_VALUE_CARD_FK	IS NOT NULL AND
              CARD_LABEL_VALUE_USER_FK	IS NULL AND
              CARD_LABEL_VALUE_LIST_VALUE_FK IS NULL
            WHEN CARD_LABEL_VALUE_TYPE = 'USER' THEN
              CARD_LABEL_VALUE_STRING 	IS NULL AND
              CARD_LABEL_VALUE_TIMESTAMP 	IS NULL AND
              CARD_LABEL_VALUE_INT 		IS NULL AND
              CARD_LABEL_VALUE_CARD_FK	IS NULL AND
              CARD_LABEL_VALUE_USER_FK	IS NOT NULL AND
              CARD_LABEL_VALUE_LIST_VALUE_FK IS NULL
            WHEN CARD_LABEL_VALUE_TYPE = 'LIST' THEN
              CARD_LABEL_VALUE_STRING 	IS NULL AND
              CARD_LABEL_VALUE_TIMESTAMP 	IS NULL AND
              CARD_LABEL_VALUE_INT 		IS NULL AND
              CARD_LABEL_VALUE_CARD_FK	IS NULL AND
              CARD_LABEL_VALUE_USER_FK	IS NULL AND
              CARD_LABEL_VALUE_LIST_VALUE_FK	IS NOT NULL
            END);
    END//
