

CREATE TABLE LA_PROJECT_MAIL_TICKET_CONFIG (
    MAIL_CONFIG_ID INTEGER AUTO_INCREMENT PRIMARY KEY NOT NULL,
    MAIL_CONFIG_NAME VARCHAR(128) NOT NULL,
    MAIL_CONFIG_PROJECT_ID_FK INTEGER NOT NULL,
    MAIL_CONFIG_ENABLED BOOLEAN DEFAULT TRUE NOT NULL,
    MAIL_CONFIG_LAST_CHECKED TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    MAIL_CONFIG_CONFIG MEDIUMTEXT,
    MAIL_CONFIG_PROPERTIES MEDIUMTEXT
) ENGINE=InnoDB CHARACTER SET=utf8 COLLATE utf8_bin;
-- CONSTRAINTS
ALTER TABLE LA_PROJECT_MAIL_TICKET_CONFIG ADD FOREIGN KEY(MAIL_CONFIG_PROJECT_ID_FK) REFERENCES LA_PROJECT(PROJECT_ID);
ALTER TABLE LA_PROJECT_MAIL_TICKET_CONFIG ADD CONSTRAINT UNIQUE_LA_PROJECT_MAIL_TICKET_CONFIG_NAME UNIQUE(MAIL_CONFIG_NAME, MAIL_CONFIG_PROJECT_ID_FK);

CREATE TABLE LA_PROJECT_MAIL_TICKET (
	MAIL_TICKET_ID INTEGER AUTO_INCREMENT PRIMARY KEY NOT NULL,
	MAIL_TICKET_NAME VARCHAR(128) NOT NULL,
	MAIL_TICKET_ENABLED BOOLEAN DEFAULT TRUE NOT NULL,
	MAIL_TICKET_ALIAS VARCHAR(254) NOT NULL,
    MAIL_TICKET_USE_ALIAS BOOLEAN DEFAULT FALSE NOT NULL,
	MAIL_TICKET_COLUMN_ID_FK INTEGER NOT NULL,
	MAIL_TICKET_CONFIG_ID_FK INTEGER NOT NULL,
	MAIL_TICKET_METADATA MEDIUMTEXT
) ENGINE=InnoDB CHARACTER SET=utf8 COLLATE utf8_bin;
-- CONSTRAINTS
ALTER TABLE LA_PROJECT_MAIL_TICKET ADD FOREIGN KEY(MAIL_TICKET_COLUMN_ID_FK) REFERENCES LA_BOARD_COLUMN(BOARD_COLUMN_ID);
ALTER TABLE LA_PROJECT_MAIL_TICKET ADD FOREIGN KEY(MAIL_TICKET_CONFIG_ID_FK) REFERENCES LA_PROJECT_MAIL_TICKET_CONFIG(MAIL_CONFIG_ID);
ALTER TABLE LA_PROJECT_MAIL_TICKET ADD CONSTRAINT UNIQUE_LA_PROJECT_MAIL_TICKET_NAME UNIQUE(MAIL_TICKET_NAME, MAIL_TICKET_CONFIG_ID_FK);
ALTER TABLE LA_PROJECT_MAIL_TICKET ADD CONSTRAINT UNIQUE_LA_PROJECT_MAIL_TICKET_ALIAS UNIQUE(MAIL_TICKET_ALIAS, MAIL_TICKET_CONFIG_ID_FK);
