

ALTER TABLE LA_PROJECT_MAIL_TICKET ADD MAIL_TICKET_SUBJECT MEDIUMTEXT;
ALTER TABLE LA_PROJECT_MAIL_TICKET ADD MAIL_TICKET_BODY MEDIUMTEXT;
ALTER TABLE LA_PROJECT_MAIL_TICKET ADD MAIL_TICKET_NOTIFICATION_OVERRIDE BOOLEAN DEFAULT FALSE NOT NULL;
