
DELETE FROM LA_ROLE_PERMISSION WHERE PERMISSION IN ('UPDATE_BOARD', 'DELETE_BOARD', 'CREATE_BOARD', 'CREATE_PROJECT');

DELETE FROM LA_PROJECT_ROLE_PERMISSION WHERE PERMISSION IN ('UPDATE_BOARD', 'DELETE_BOARD', 'CREATE_BOARD', 'CREATE_PROJECT');
