

ALTER TABLE LA_API_HOOK ADD API_HOOK_ENABLED BOOLEAN NOT NULL;
ALTER TABLE LA_API_HOOK ADD API_HOOK_TYPE VARCHAR(32) NOT NULL;
ALTER TABLE LA_API_HOOK ADD API_HOOK_PROJECTS CLOB;
ALTER TABLE LA_API_HOOK ADD API_HOOK_VERSION INTEGER NOT NULL;
