

ALTER TABLE LA_PROJECT_MAIL_TICKET ADD MAIL_TICKET_SUBJECT CLOB;
ALTER TABLE LA_PROJECT_MAIL_TICKET ADD MAIL_TICKET_BODY CLOB;
ALTER TABLE LA_PROJECT_MAIL_TICKET ADD MAIL_TICKET_NOTIFICATION_OVERRIDE BOOLEAN DEFAULT FALSE NOT NULL;
