
CREATE TABLE LA_USER_CALENDAR (
	USER_CALENDAR_TOKEN CHAR(64) NOT NULL,
	USER_CALENDAR_ID_FK INTEGER NOT NULL,
	PRIMARY KEY(USER_CALENDAR_ID_FK)
);
-- CONSTRAINTS
ALTER TABLE LA_USER_CALENDAR ADD FOREIGN KEY(USER_CALENDAR_ID_FK) REFERENCES LA_USER(USER_ID);
