
DELETE FROM LA_ROLE_PERMISSION WHERE PERMISSION IN ('CREATE_LABEL', 'UPDATE_LABEL', 'DELETE_LABEL');
DELETE FROM LA_PROJECT_ROLE_PERMISSION WHERE PERMISSION IN ('CREATE_LABEL', 'UPDATE_LABEL', 'DELETE_LABEL');



INSERT INTO LA_ROLE_PERMISSION(ROLE_ID_FK, PERMISSION) SELECT DISTINCT ROLE_ID_FK, 'MANAGE_ACTION_LIST' FROM LA_ROLE_PERMISSION WHERE PERMISSION IN
(
'CREATE_ACTION_LIST',
'DELETE_ACTION_LIST',
'UPDATE_ACTION_LIST',
'ORDER_ACTION_LIST',
'CREATE_ACTION_LIST_ITEM',
'DELETE_ACTION_LIST_ITEM',
'TOGGLE_ACTION_LIST_ITEM',
'UPDATE_ACTION_LIST_ITEM',
'MOVE_ACTION_LIST_ITEM'
);
INSERT INTO LA_PROJECT_ROLE_PERMISSION(PROJECT_ROLE_ID_FK, PERMISSION) SELECT DISTINCT PROJECT_ROLE_ID_FK, 'MANAGE_ACTION_LIST' FROM LA_PROJECT_ROLE_PERMISSION WHERE PERMISSION IN
(
'CREATE_ACTION_LIST',
'DELETE_ACTION_LIST',
'UPDATE_ACTION_LIST',
'ORDER_ACTION_LIST',
'CREATE_ACTION_LIST_ITEM',
'DELETE_ACTION_LIST_ITEM',
'TOGGLE_ACTION_LIST_ITEM',
'UPDATE_ACTION_LIST_ITEM',
'MOVE_ACTION_LIST_ITEM'
);
DELETE FROM LA_ROLE_PERMISSION WHERE PERMISSION IN (
'CREATE_ACTION_LIST',
'DELETE_ACTION_LIST',
'UPDATE_ACTION_LIST',
'ORDER_ACTION_LIST',
'CREATE_ACTION_LIST_ITEM',
'DELETE_ACTION_LIST_ITEM',
'TOGGLE_ACTION_LIST_ITEM',
'UPDATE_ACTION_LIST_ITEM',
'MOVE_ACTION_LIST_ITEM'
);
DELETE FROM LA_PROJECT_ROLE_PERMISSION WHERE PERMISSION IN (
'CREATE_ACTION_LIST',
'DELETE_ACTION_LIST',
'UPDATE_ACTION_LIST',
'ORDER_ACTION_LIST',
'CREATE_ACTION_LIST_ITEM',
'DELETE_ACTION_LIST_ITEM',
'TOGGLE_ACTION_LIST_ITEM',
'UPDATE_ACTION_LIST_ITEM',
'MOVE_ACTION_LIST_ITEM'
);
