
package io.collapp.query;

import ch.digitalfondue.npjt.Query;
import ch.digitalfondue.npjt.QueryRepository;

@QueryRepository
public interface MySqlFullTextSupportQuery {

	@Query("INSERT INTO LA_CARD_FTS_SUPPORT SELECT CARD_ID,CARD_NAME,CARD_LAST_UPDATED FROM LA_CARD left join LA_CARD_FTS_SUPPORT ON CARD_ID = CARD_FTS_SUPPORT_CARD_ID_FK WHERE CARD_FTS_SUPPORT_CARD_ID_FK IS NULL LIMIT 1000")
	int syncNewCards();

	@Query("REPLACE INTO LA_CARD_FTS_SUPPORT SELECT CARD_ID,CARD_NAME,CARD_LAST_UPDATED FROM LA_CARD left join LA_CARD_FTS_SUPPORT ON CARD_ID = CARD_FTS_SUPPORT_CARD_ID_FK WHERE CARD_LAST_UPDATED <> CARD_FTS_SUPPORT_LAST_UPDATED LIMIT 1000")
	int syncUpdatedCards();

	@Query("INSERT INTO LA_CARD_DATA_FTS_SUPPORT SELECT CARD_DATA_ID,CARD_DATA_CONTENT,CARD_DATA_LAST_UPDATED FROM LA_CARD_DATA left join LA_CARD_DATA_FTS_SUPPORT ON CARD_DATA_ID = CARD_DATA_FTS_SUPPORT_CARD_DATA_ID_FK WHERE CARD_DATA_FTS_SUPPORT_CARD_DATA_ID_FK IS NULL LIMIT 1000")
	int syncNewCardData();

	@Query("REPLACE INTO LA_CARD_DATA_FTS_SUPPORT SELECT CARD_DATA_ID,CARD_DATA_CONTENT,CARD_DATA_LAST_UPDATED FROM LA_CARD_DATA left join LA_CARD_DATA_FTS_SUPPORT ON CARD_DATA_ID = CARD_DATA_FTS_SUPPORT_CARD_DATA_ID_FK WHERE CARD_DATA_LAST_UPDATED <> CARD_DATA_FTS_SUPPORT_LAST_UPDATED LIMIT 1000")
	int syncUpdatedCardData();
}
