
package io.collapp.model

import java.util.*

class ImportContext {
    // map the ids from the imported file to the ids generated by the system
    val columns: Map<Int, Int> = HashMap()
    val commentsId: Map<Int, Int> = HashMap()
    val actionListId: Map<Int, Int> = HashMap()
    val actionItemId: Map<Int, Int> = HashMap()
    val fileId: Map<Int, Int> = HashMap()
    //

    val importedProject: Set<String> = HashSet()
    val importedBoard: Set<String> = HashSet()
}
